<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="$(ProjectDir)..\.props" />

	<PropertyGroup>
		<TargetFrameworks>netstandard2.1;net10.0</TargetFrameworks>
		<Configurations>Debug;Release</Configurations>
		<BaseOutputPath>$(ProjectDir)..\..\Basis Server Export\$(MSBuildProjectName)\bin\</BaseOutputPath>
		<GeneratePackageOnBuild Condition="'$(Configuration)'=='Release'">true</GeneratePackageOnBuild>
		<LangVersion>13</LangVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Debug'">
		<DefineConstants>TRACE;DEBUG</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="BasisNetworkServer\**" />
		<EmbeddedResource Remove="BasisNetworkServer\**" />
		<None Remove="BasisNetworkServer\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="K4os.Compression.LZ4" Version="1.3.8" />
		<PackageReference Include="System.Text.Json" Version="9.0.0" Condition="'$(TargetFramework)' == 'netstandard2.1'" />
		<ProjectReference Include="..\BasisNetworkCore\BasisNetworkCore.csproj" />
		<ProjectReference Include="..\Contrib\Auth\Did\Did.csproj" />
		<ProjectReference Include="..\Contrib\Crypto\Crypto.csproj" />
		<ProjectReference Include="..\LiteNetLib\LiteNetLib.csproj" />
	</ItemGroup>

	<PropertyGroup>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="BasisServerTests" />
		<InternalsVisibleTo Include="BasisRestApi.Tests" />
	</ItemGroup>
</Project>
